language: cpp

matrix:
  include:
    - compiler: gcc
      os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
      env:
        - COMPILER=g++-4.9
        - GCOV=/usr/bin/gcov-4.9
    - compiler: gcc
      os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env:
        - COMPILER=g++-5
        - GCOV=/usr/bin/gcov-5
    - compiler: clang
      os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.6
          packages:
            - clang-3.6
      env:
        - COMPILER=clang++-3.6
        - GCOV=/usr/bin/gcov
    - compiler: clang
      os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.7
          packages:
            - clang-3.7
      env:
        - COMPILER=clang++-3.7
        - GCOV=/usr/bin/gcov
    - compiler: gcc
      os: osx
      env:
        - COMPILER=g++
        - GCOV=/usr/bin/gcov
        # a2x will run xmllint on generated files, so we have to pass the path
        # to AsciiDoc's catalog files
        - XML_CATALOG_FILES=/usr/local/etc/xml/catalog
    - compiler: clang
      os: osx
      env:
        - COMPILER=clang++
        - GCOV=/usr/bin/gcov
        # a2x will run xmllint on generated files, so we have to pass the path
        # to AsciiDoc's catalog files
        - XML_CATALOG_FILES=/usr/local/etc/xml/catalog

install:
    - export CXX=$COMPILER
    - cd ${TRAVIS_BUILD_DIR}
    - ./travis-get-deps.sh

script:
    - cd ${TRAVIS_BUILD_DIR}
    - make PROFILE=1 all test
    - ( cd test && ./test --order rand )
    - make run-i18nspector | tee i18nspector.log && egrep '^E:' i18nspector.log && exit 1

after_success:
    - cd ${TRAVIS_BUILD_DIR}
    - ./submit-to-coveralls.sh
